dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: rom-import-5
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom32
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom33
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom37
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rom45
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
